DontJoinThisCompany.Web/Controllers/CompanyDetails/CompanyDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using DontJoinThisCompany.Business.CompanyQueries;
using DontJoinThisCompany.Models.CompanyAndUserExperience;
using DontJoinThisCompany.Business.UserExperienceQueries;
namespace DontJoinThisCompany.Web.Controllers.CompanyDetails
{
    public class CompanyDetailsController : Controller
    {
        
        CompanyDetailsQueries companyDetails = new CompanyDetailsQueries();
        public ActionResult AllCompanies(int? page)
        {
            return View(companyDetails.GetAllCompanies().ToPagedList(page ??1,15));
        }
        public ActionResult GetcompanyById(int id)
        {
            CompanyAndUserExperienceModel model = new CompanyAndUserExperienceModel();
            UserExperienceDetailsQueries userExperiences = new UserExperienceDetailsQueries();
            model = userExperiences.GetUserExperienceByCompanyId(id);
            model.CompanyDetails = companyDetails.GetCompanyById(id); 
            return View(model);
        }
        [HttpPost]
        public JsonResult UpdateRating(double RatedValue, int CompanyId)
        {
             if(Request.IsAuthenticated)
             {
                var company= companyDetails.GetCompanyById(CompanyId);
                company.CompanyRating = RatedValue;
                companyDetails.UpdateCompanyRating(company);
                return new JsonResult { Data = new { sucess = true, msg = "" } };
             }
             return new JsonResult { Data = new { sucess = false, msg = "Not updated" } };
        }

        public JsonResult AutoCompleteForCompanies(string term)
        {
            return  Json(companyDetails.AutoCompleteforCompanies(term), JsonRequestBehavior.AllowGet);
        }
    }
}

DontJoinThisCompany.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dont Join This company</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="/Content/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="/Content/css/style.css" rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,300,600,700|Six+Caps' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="/Content/css/flexslider.css" type="text/css" media="screen" />
    <script src="/Content/js/jquery.min.js"></script>
    <link href="~/Content/css/rateit.css" rel="stylesheet" />
    <link href="~/Content/css/PagedList.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.rateit.js"></script>
    <link href="~/Content/css/Pop-up.css" rel="stylesheet" />
    <script type="text/javascript" src="/Content/js/bootstrap.js"></script>
</head>
<body>
    <!--header-top-starts-->
    <div class="header-top">
        <div class="container">
            <div class="head-main">
                <h1><a href="/Home">DJC</a></h1>
            </div>
            @Html.Partial("_LoginPartial")
            <div class="navigation">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!--/.navbar-header-->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="/Home">Home</a></li>
                            <li><a href="/CompanyDetails/AllCompanies">Companies</a></li>
                            <li><a href="">Contact</a></li>
                        </ul>
                    </div>
                    <!--/.navbar-collapse-->
                </nav>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <!--header-top-end-->
    <!--start-header-->
    <div class="header">
        <div class="container">
            <div class="head">
                <div class="soc">
                    <ul>
                        <li><a href="#"><span class="fb"> </span></a></li>
                        <li><a href="#"><span class="twit"> </span></a></li>
                        <li><a href="#"><span class="pin"> </span></a></li>
                        <li><a href="#"><span class="rss"> </span></a></li>
                        <li><a href="#"><span class="drbl"> </span></a></li>
                        <div class="clearfix"></div>
                    </ul>
                </div>
                <div class="header-right">
                    <div class="search-bar">
                        <form action="/SearchForComapny/SearchTheCompanies" method="post">
                            <input type="text" id="autocomplete" name="searchKeyword" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
                            <input type="submit" value="">
                        </form>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!-- script-for-autocomplete -->
    <script src="~/Scripts/jquery-ui-1.9.2.custom.min.js"></script>
    <link href="~/Content/css/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" />
    <script>
        $('#autocomplete').autocomplete({
            source: '@Url.Action("AutoCompleteForCompanies", "CompanyDetails")'
        });
    </script>
    <!-- script-for-autocomplete -->
    <!-- script-for-menu -->
    <!-- script-for-menu -->
    <script>
        $("span.menu").click(function () {
            $(" ul.navig").slideToggle("slow", function () {
            });
        });
    </script>
    <!-- script-for-menu -->
    @RenderBody()
    <!-- footer-starts -->
    <div class="footer">
        <div class="container">
            <div class="col-md-4 contact-left">
                <h4>Address</h4>
                <div class="cont-tp">
                    <span class="glyphicon glyphicon-map-marker" aria-hidden="true">
                    </span>
                </div>

                <address>
                    795 Folsom Ave, Suite 600<br>
                    San Francisco, CA 94107<br>
                    <abbr title="Phone">P :</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-md-4 contact-left">
                <h4>Phone/Fax</h4>
                <div class="cont-tp">
                    <span class="glyphicon glyphicon-phone" aria-hidden="true">
                    </span>
                </div>

                <p>Phone : +1234567890 </p>
                <p>Phone : +1234567890 </p>
                <p>Fax : +1234567890 </p>
            </div>
            <div class="col-md-4 contact-left">
                <h4>Newsletter</h4>
                <div class="cont-tp">
                    <span class="glyphicon glyphicon-envelope" aria-hidden="true">
                    </span>
                </div>
                <form>
                    <input type="text" value="Enter Your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your email';}">
                    <input type="submit" value="Subscribe">
                </form>
            </div>
            <div class="clearfix"></div>

            <div class="footer-text">
                <p>© 2016 Law. All Rights Reserved | Build by LohithaPalagiri </p>
            </div>
        </div>
    </div>
    <!-- footer-end -->
</body>
</html>